# Data Preperation - adapted from Prof. Kyle Whynott’s CPSC 483 Intro to ML course

## 1. Data Set Selection

### Sources to Acquire Datasets From

- [Kaggle](https://www.kaggle.com/datasets)

- [UCI Machine Learning Repository](https://archive.ics.uci.edu/)

- [Data.Gov](https://data.gov/)

- [World Bank Open Data](https://data.worldbank.org/)

- [Awesome Public Datsets](https://github.com/awesomedata/awesome-public-datasets)

### Code Documentation

- [Numpy](https://numpy.org/)

- [Pandas](https://pandas.pydata.org/)

## 2. Import the Dataset

In [46]:
import numpy as np
import pandas as pd
import os

In [47]:
# Show all columns in Jupyter Lab using Pandas
import pandas as pd
import os
pd.set_option('display.max_columns', None)

In [48]:
# Insert Dataset Here (Code to Be Completed)
import pandas as pd

# Option 1: Correct the file path if you know where the file is located
# For example, if it's in a different directory:
# df = pd.read_csv("../data/air_quality/AirQualityUCI.csv", sep=";", decimal=",")

# Option 2: If you don't have the file locally, download it from a public source
import urllib.request
import os

# Create directories if they don't exist
os.makedirs("./dataset/air_quality", exist_ok=True)

# Download the file from UCI repository
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip"
zip_path = "./dataset/air_quality/AirQualityUCI.zip"
urllib.request.urlretrieve(url, zip_path)

# Extract the zip file
import zipfile
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("./dataset/air_quality/")

# Now read the CSV file
df = pd.read_csv("./dataset/air_quality/AirQualityUCI.csv", sep=";", decimal=",")

In [49]:
display(df.head())

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

## 3. Look for Data that Needs to Be Dropped / Cleaned

In [50]:
# Drop Rows with NaN values
import pandas as pd
import urllib.request
import os
import zipfile

# Create directories if they don't exist
os.makedirs("./dataset/air_quality", exist_ok=True)

# Download the file from UCI repository
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip"
zip_path = "./dataset/air_quality/AirQualityUCI.zip"
urllib.request.urlretrieve(url, zip_path)

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("./dataset/air_quality/")

# Now read the CSV file
df = pd.read_csv("./dataset/air_quality/AirQualityUCI.csv", sep=";", decimal=",")

# To do list for cleaning the data
# Replace -200 with NaN (need to specify what to replace and what to replace it with)
df = df.replace(-200, pd.NA)  

# Drop columns with all NaN values (axis=1 for columns)
df = df.dropna(axis=1, how='all')  

# Drop rows with any NaN values (axis=0 for rows, which is default)
df = df.dropna(how='any')  

# Check how many rows left after cleaning
print(f"Number of rows after cleaning: {len(df)}")

Number of rows after cleaning: 827

In [51]:
# Drop Rows with NaN values
import pandas as pd
import urllib.request
import os
import zipfile

# Create directories if they don't exist
os.makedirs("./dataset/air_quality", exist_ok=True)

# Download the file from UCI repository
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip"
zip_path = "./dataset/air_quality/AirQualityUCI.zip"
urllib.request.urlretrieve(url, zip_path)

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("./dataset/air_quality/")

# List files in the directory to see what's actually there
print("Files in the directory:")
print(os.listdir("./dataset/air_quality/"))

# Now read the CSV file - using the correct path based on the extracted files
# The exact filename might be different, adjust if needed
try:
    df = pd.read_csv("./dataset/air_quality/AirQualityUCI.csv", sep=";", decimal=",")
except FileNotFoundError:
    # Try alternative paths that might exist after extraction
    try:
        df = pd.read_csv("./dataset/air_quality/AirQualityUCI/AirQualityUCI.csv", sep=";", decimal=",")
    except FileNotFoundError:
        # If still not found, list all files recursively to help identify the correct path
        for root, dirs, files in os.walk("./dataset"):
            for file in files:
                if file.endswith(".csv"):
                    print(f"Found CSV file: {os.path.join(root, file)}")
        raise

# To do list for cleaning the data
# Replace -200 with NaN (need to specify what to replace and what to replace it with)
df = df.replace(-200, pd.NA)  

# Drop columns with all NaN values (axis=1 for columns)
df = df.dropna(axis=1, how='all')  

# Drop rows with any NaN values (axis=0 for rows, which is default)
df = df.dropna(how='any')  

# Check how many rows left after cleaning
print(f"Number of rows after cleaning: {len(df)}")

Files in the directory:
['AirQualityUCI.csv', 'AirQualityUCI.xlsx', 'AirQualityUCI.zip']
Number of rows after cleaning: 827

In [52]:
display(df)

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,30/04/2004,20.00.00,4.4,1449.0,501.0,19.5,1282.0,254.0,625.0,133.0,2100.0,1569.0,19.1,61.1,1.3345
1227,30/04/2004,21.00.00,3.1,1363.0,234.0,15.1,1152.0,189.0,684.0,110.0,1951.0,1495.0,18.2,65.4,1.3529
1228,30/04/2004,22.00.00,3.0,1371.0,212.0,14.6,1136.0,174.0,689.0,102.0,1927.0,1471.0,18.1,66.1,1.3579
1229,30/04/2004,23.00.00,3.1,1406.0,275.0,13.7,1107.0,167.0,718.0,108.0,1872.0,1384.0,17.7,66.9,1.3422
1230,01/05/2004,00.00.00,3.5,1425.0,275.0,15.2,1155.0,185.0,709.0,110.0,1936.0,1789.0,17.8,66.8,1.346

In [53]:
#select features and label
target = "CO(GT)"
X2 = df.drop(columns=[target]) #X features
y2 = df[target] #y: label

In [54]:
X2.shape  # (n_samples, n_features)
y2.shape  # (n_samples,)
print(X2.shape)
print(y2.shape)

(827, 14)
(827,)

## 4. Split the data into Training(70%)/Valitation(15%)/Testing(%15)

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X2, y2,
    test_size=0.30,      # 30% left for val + test
    random_state=42
)
print(X_train.shape)  # (n_samples_train, n_features)
print(y_train.shape)  # (n_labels_train,)

(578, 14)
(578,)

In [56]:
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,      # split 30% into 15% / 15%
    random_state=42
)
print(X_val.shape)  # (n_samples_train, n_features)
print(y_val.shape)  # (n_labels_train,)
print(X_test.shape)  # (n_samples_train, n_features)
print(y_test.shape)  # (n_labels_train,)

(124, 14)
(124,)
(125, 14)
(125,)

## 5. Now, let's use the built-in python code from the UCI database ###

In [57]:
# if you did it before--> %pip install ucimlrepo, you can skip this step

In [58]:
!pip install ucimlrepo
import ucimlrepo
from ucimlrepo import fetch_ucirepo
print("ucimlrepo is installed")

Requirement already satisfied: ucimlrepo in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from ucimlrepo) (3.0.0)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\troy\downloads\cpsc483_spring_2026\lab-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
ucimlrepo is installed

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
air_quality = fetch_ucirepo(id=360)

# data (as pandas dataframes)
X = air_quality.data.features
y = air_quality.data.targets

# metadata
print(air_quality.metadata)

# variable information
print(air_quality.variables)

{'uci_id': 360, 'name': 'Air Quality', 'repository_url': 'https://archive.ics.uci.edu/dataset/360/air+quality', 'data_url': 'https://archive.ics.uci.edu/static/public/360/data.csv', 'abstract': 'Contains the responses of a gas multisensor device deployed on the field in an Italian city. Hourly responses averages are recorded along with gas concentrations references from a certified analyzer. ', 'area': 'Computer Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate', 'Time-Series'], 'num_instances': 9358, 'num_features': 15, 'feature_types': ['Real'], 'demographics': [], 'target_col': None, 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2008, 'last_updated': 'Sun Mar 10 2024', 'dataset_doi': '10.24432/C59K5F', 'creators': ['Saverio Vito'], 'intro_paper': {'ID': 420, 'type': 'NATIVE', 'title': 'On field calibration of an electronic nose for benzene estimation in an urban pollution monitoring scenario', 'authors': 'S. D. Vito, E. Massera, M. Piga, L. Martinotto, G. Francia', 'venue': 'Sensors and Actuators B: Chemical', 'year': 2008, 'journal': None, 'DOI': '10.1016/j.snb.2007.09.060', 'URL': 'https://www.semanticscholar.org/paper/a90a54a39ff934772df57771a0012981f355949d', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The dataset contains 9358 instances of hourly averaged responses from an array of 5 metal oxide chemical sensors embedded in an Air Quality Chemical Multisensor Device. The device was located on the field in a significantly polluted area, at road level,within an Italian city. Data were recorded from March 2004 to February 2005 (one year)representing the longest freely available recordings of on field deployed air quality chemical sensor devices responses. Ground Truth hourly averaged concentrations for CO, Non Metanic Hydrocarbons, Benzene, Total Nitrogen Oxides (NOx) and Nitrogen Dioxide (NO2)  and were provided by a co-located reference certified analyzer. Evidences of cross-sensitivities as well as both concept and sensor drifts are present as described in De Vito et al., Sens. And Act. B, Vol. 129,2,2008 (citation required) eventually affecting sensors concentration estimation capabilities. Missing values are tagged with -200 value.\r\nThis dataset can be used exclusively for research purposes. Commercial purposes are fully excluded.\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '0 Date\t(DD/MM/YYYY)\r\n1 Time\t(HH.MM.SS)\r\n2 True hourly averaged concentration CO in mg/m^3  (reference analyzer)\r\n3 PT08.S1 (tin oxide)  hourly averaged sensor response (nominally  CO targeted)\t\r\n4 True hourly averaged overall Non Metanic HydroCarbons concentration in microg/m^3 (reference analyzer)\r\n5 True hourly averaged Benzene concentration  in microg/m^3 (reference analyzer)\r\n6 PT08.S2 (titania) hourly averaged sensor response (nominally NMHC targeted)\t\r\n7 True hourly averaged NOx concentration  in ppb (reference analyzer)\r\n8 PT08.S3 (tungsten oxide) hourly averaged sensor response (nominally NOx targeted) \r\n9 True hourly averaged NO2 concentration in microg/m^3 (reference analyzer)\t\r\n10 PT08.S4 (tungsten oxide) hourly averaged sensor response (nominally NO2 targeted)\t\r\n11 PT08.S5 (indium oxide) hourly averaged sensor response (nominally O3 targeted)\r\n12 Temperature in Â°C\t\r\n13 Relative Humidity (%) \t\r\n14 AH Absolute Humidity\r\n', 'citation': None}}
             name     role         type demographic  \
0            Date  Feature         Date        None
1            Time  Feature  Categorical        None
2          CO(GT)  Feature      Integer        None
3     PT08.S1(CO)  Feature  Categorical        None
4        NMHC(GT)  Feature      Integer        None
5        C6H6(GT)  Feature   Continuous        None
6   PT08.S2(NMHC)  Feature  Categorical        None
7         NOx(GT)  Feature      Integer        None
8    PT08.S3(NOx)  Feature  Categorical        None
9         NO2(GT)  Feature      Integer        None
10   PT08.S4(NO2)  Feature  Categorical        None
11    PT08.S5(O3)  Feature  Categorical        None
12              T  Feature   Continuous        None
13             RH  Feature   Continuous        None
14             AH  Feature   Continuous        None

                                          description       units  \
0                                                 NaN         NaN
1                                                 NaN         NaN
2   True hourly averaged concentration CO in mg/m^...      mg/m^3
3   hourly averaged sensor response (nominally  CO...         NaN
4   True hourly averaged overall Non Metanic Hydro...  microg/m^3
5   True hourly averaged Benzene concentration  in...  microg/m^3
6   hourly averaged sensor response (nominally NMH...         NaN
7   True hourly averaged NOx concentration  in ppb...         ppb
8   hourly averaged sensor response (nominally NOx...         NaN
9   True hourly averaged NO2 concentration in micr...  microg/m^3
10  hourly averaged sensor response (nominally NO2...         NaN
11  hourly averaged sensor response (nominally O3 ...         NaN
12                                        Temperature          °C
13                                  Relative Humidity           %
14                                  Absolute Humidity         NaN

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no

In [60]:
# print details of metadata (find indication of missing values)

from pprint import pprint
pprint(air_quality.metadata)

{'abstract': 'Contains the responses of a gas multisensor device deployed on '
             'the field in an Italian city. Hourly responses averages are '
             'recorded along with gas concentrations references from a '
             'certified analyzer. ',
 'additional_info': {'citation': None,
                     'funded_by': None,
                     'instances_represent': None,
                     'preprocessing_description': None,
                     'purpose': None,
                     'recommended_data_splits': None,
                     'sensitive_data': None,
                     'summary': 'The dataset contains 9358 instances of hourly '
                                'averaged responses from an array of 5 metal '
                                'oxide chemical sensors embedded in an Air '
                                'Quality Chemical Multisensor Device. The '
                                'device was located on the field in a '
                                'significantly polluted area, at road '
                                'level,within an Italian city. Data were '
                                'recorded from March 2004 to February 2005 '
                                '(one year)representing the longest freely '
                                'available recordings of on field deployed air '
                                'quality chemical sensor devices responses. '
                                'Ground Truth hourly averaged concentrations '
                                'for CO, Non Metanic Hydrocarbons, Benzene, '
                                'Total Nitrogen Oxides (NOx) and Nitrogen '
                                'Dioxide (NO2)  and were provided by a '
                                'co-located reference certified analyzer. '
                                'Evidences of cross-sensitivities as well as '
                                'both concept and sensor drifts are present as '
                                'described in De Vito et al., Sens. And Act. '
                                'B, Vol. 129,2,2008 (citation required) '
                                'eventually affecting sensors concentration '
                                'estimation capabilities. Missing values are '
                                'tagged with -200 value.\r\n'
                                'This dataset can be used exclusively for '
                                'research purposes. Commercial purposes are '
                                'fully excluded.\r\n',
                     'variable_info': '0 Date\t(DD/MM/YYYY)\r\n'
                                      '1 Time\t(HH.MM.SS)\r\n'
                                      '2 True hourly averaged concentration CO '
                                      'in mg/m^3  (reference analyzer)\r\n'
                                      '3 PT08.S1 (tin oxide)  hourly averaged '
                                      'sensor response (nominally  CO '
                                      'targeted)\t\r\n'
                                      '4 True hourly averaged overall Non '
                                      'Metanic HydroCarbons concentration in '
                                      'microg/m^3 (reference analyzer)\r\n'
                                      '5 True hourly averaged Benzene '
                                      'concentration  in microg/m^3 (reference '
                                      'analyzer)\r\n'
                                      '6 PT08.S2 (titania) hourly averaged '
                                      'sensor response (nominally NMHC '
                                      'targeted)\t\r\n'
                                      '7 True hourly averaged NOx '
                                      'concentration  in ppb (reference '
                                      'analyzer)\r\n'
                                      '8 PT08.S3 (tungsten oxide) hourly '
                                      'averaged sensor response (nominally NOx '
                                      'targeted) \r\n'
                                      '9 True hourly averaged NO2 '
                                      'concentration in microg/m^3 (reference '
                                      'analyzer)\t\r\n'
                                      '10 PT08.S4 (tungsten oxide) hourly '
                                      'averaged sensor response (nominally NO2 '
                                      'targeted)\t\r\n'
                                      '11 PT08.S5 (indium oxide) hourly '
                                      'averaged sensor response (nominally O3 '
                                      'targeted)\r\n'
                                      '12 Temperature in Â°C\t\r\n'
                                      '13 Relative Humidity (%) \t\r\n'
                                      '14 AH Absolute Humidity\r\n'},
 'area': 'Computer Science',
 'characteristics': ['Multivariate', 'Time-Series'],
 'creators': ['Saverio Vito'],
 'data_url': 'https://archive.ics.uci.edu/static/public/360/data.csv',
 'dataset_doi': '10.24432/C59K5F',
 'demographics': [],
 'feature_types': ['Real'],
 'has_missing_values': 'no',
 'index_col': None,
 'intro_paper': {'DOI': '10.1016/j.snb.2007.09.060',
                 'ID': 420,
                 'URL': 'https://www.semanticscholar.org/paper/a90a54a39ff934772df57771a0012981f355949d',
                 'acl': None,
                 'arxiv': None,
                 'authors': 'S. D. Vito, E. Massera, M. Piga, L. Martinotto, '
                            'G. Francia',
                 'corpus': None,
                 'journal': None,
                 'mag': None,
                 'pmcid': None,
                 'pmid': None,
                 'sha': None,
                 'title': 'On field calibration of an electronic nose for '
                          'benzene estimation in an urban pollution monitoring '
                          'scenario',
                 'type': 'NATIVE',
                 'venue': 'Sensors and Actuators B: Chemical',
                 'year': 2008},
 'last_updated': 'Sun Mar 10 2024',
 'missing_values_symbol': None,
 'name': 'Air Quality',
 'num_features': 15,
 'num_instances': 9358,
 'repository_url': 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'target_col': None,
 'tasks': ['Regression'],
 'uci_id': 360,
 'year_of_dataset_creation': 2008}

In [61]:
X = air_quality.data.features

In [62]:
print(X.shape)

(9357, 15)

In [63]:
display(X.head(10))#show first 10 rows

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
5,3/10/2004,23:00:00,1.2,1197,38,4.7,750,89,1337,96,1393,949,11.2,59.2,0.7848
6,3/11/2004,0:00:00,1.2,1185,31,3.6,690,62,1462,77,1333,733,11.3,56.8,0.7603
7,3/11/2004,1:00:00,1.0,1136,31,3.3,672,62,1453,76,1333,730,10.7,60.0,0.7702
8,3/11/2004,2:00:00,0.9,1094,24,2.3,609,45,1579,60,1276,620,10.7,59.7,0.7648
9,3/11/2004,3:00:00,0.6,1010,19,1.7,561,-200,1705,-200,1235,501,10.3,60.2,0.7517

In [64]:
# show current y if defined
try:
	display(y)
except NameError:
	print("y not defined yet")

# show available columns in X
print("X columns:", X.columns.tolist())

# Move CO(GT) from features X into target y
if 'CO(GT)' in X.columns:
	# pop returns the column and removes it from X
	y = X.pop('CO(GT)')
else:
	# fallback: use df if it has the target column
	if 'df' in globals() and 'CO(GT)' in df.columns:
		y = df['CO(GT)']
		X = df.drop(columns=['CO(GT)'])
	else:
		raise KeyError("CO(GT) column not found in X or df")

display(y.head())
display(X.head())

None

X columns: ['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']

0    2.6
1    2.0
2    2.2
3    2.2
4    1.6
Name: CO(GT), dtype: float64

,Date,Time,PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [65]:
#Show more details about the data
type(X)
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   str
 1   Time           9357 non-null   str
 2   PT08.S1(CO)    9357 non-null   int64
 3   NMHC(GT)       9357 non-null   int64
 4   C6H6(GT)       9357 non-null   float64
 5   PT08.S2(NMHC)  9357 non-null   int64
 6   NOx(GT)        9357 non-null   int64
 7   PT08.S3(NOx)   9357 non-null   int64
 8   NO2(GT)        9357 non-null   int64
 9   PT08.S4(NO2)   9357 non-null   int64
 10  PT08.S5(O3)    9357 non-null   int64
 11  T              9357 non-null   float64
 12  RH             9357 non-null   float64
 13  AH             9357 non-null   float64
dtypes: float64(4), int64(8), str(2)
memory usage: 1023.6 KB

In [66]:
# Describe the data (include some statistics)
X.describe()

,PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,1048.990061,-159.090093,1.865683,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,9.778305,39.485380,-6.837604
std,329.832710,139.789093,41.380206,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,43.203623,51.216145,38.976670
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,921.000000,-200.000000,4.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,10.900000,34.100000,0.692300
50%,1053.000000,-200.000000,7.900000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,17.200000,48.600000,0.976800
75%,1221.000000,-200.000000,13.600000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,24.100000,61.900000,1.296200
max,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000

In [67]:
#check for missing values
X.isna().sum()

Date             0
Time             0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [68]:
#check first column values
X = air_quality.data.features
X.iloc[:, 0]

0       3/10/2004
1       3/10/2004
2       3/10/2004
3       3/10/2004
4       3/10/2004
          ...
9352     4/4/2005
9353     4/4/2005
9354     4/4/2005
9355     4/4/2005
9356     4/4/2005
Name: Date, Length: 9357, dtype: str

In [69]:
#check data type of first column
#check data type of 4th column
# Ensure X is defined (use X2 if available)
if 'X' not in globals():
	X = X2

print(X.iloc[:, 0].dtype)
print(X.iloc[:, 3].dtype)
display(X.iloc[0:10, 3])
display(X.head(10))

str
int64

0    150
1    112
2     88
3     80
4     51
5     38
6     31
7     31
8     24
9     19
Name: NMHC(GT), dtype: int64

,Date,Time,PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
5,3/10/2004,23:00:00,1197,38,4.7,750,89,1337,96,1393,949,11.2,59.2,0.7848
6,3/11/2004,0:00:00,1185,31,3.6,690,62,1462,77,1333,733,11.3,56.8,0.7603
7,3/11/2004,1:00:00,1136,31,3.3,672,62,1453,76,1333,730,10.7,60.0,0.7702
8,3/11/2004,2:00:00,1094,24,2.3,609,45,1579,60,1276,620,10.7,59.7,0.7648
9,3/11/2004,3:00:00,1010,19,1.7,561,-200,1705,-200,1235,501,10.3,60.2,0.7517

## 6. You can use similar way to split the training/validation/testing data

In [70]:
#To do list 70/15/15 split

from sklearn.model_selection import train_test_split

# 70/15/15 split using X and y (drops Date/Time if present, ensures y is numeric)
y = pd.to_numeric(y, errors='coerce')
mask = y.notna()
X = X.loc[mask]
y = y.loc[mask]

# drop non-feature columns
X_features = X.drop(columns=['Date', 'Time'], errors='ignore')

# split 70/30 then 50/50 of the 30% to get 70/15/15

X_train, X_temp, y_train, y_temp = train_test_split(
    X_features, y, test_size=0.30, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42
)

print("Shapes ->",
      "X_train:", X_train.shape,
      "X_val:", X_val.shape,
      "X_test:", X_test.shape,
      "y_train:", y_train.shape,
      "y_val:", y_val.shape,
      "y_test:", y_test.shape)

Shapes -> X_train: (6549, 12) X_val: (1404, 12) X_test: (1404, 12) y_train: (6549,) y_val: (1404,) y_test: (1404,)